scientist-softserv/webstore-component-library

src/compounds/ItemGroup/ItemGroup.jsx
src/compounds/ItemGroup/ItemGroup.stories.jsx
src/compounds/ItemGroup/item-group.css

- give ItemGroup a loading state

24 item group loading

---

src/pages/Home.stories.jsx

- there is no longer an [ItemGroup example](https://github.com/scientist-softserv/webstore-component-library/blob/main/src/compounds/ItemGroup/ItemGroup.stories.jsx) titled "Alternate" so I fixed the import for the Home story per the console warning

home story import

---

src/components/Loading/Loading.jsx
src/compounds/ItemPage/ItemPage.jsx
src/compounds/ItemPage/item-page.css

- add padding to the top and bottom of the item page

item page styling

---

src/compounds/RequestItem/RequestItem.jsx
src/compounds/RequestItem/RequestItem.stories.jsx
src/compounds/RequestItem/request-item.css
src/compounds/index.js
src/resources/args.js

- remove the img import from the RequestItem component because it caused the rollup build to fail for some reason: "Note that you need plugins to import files that are not JavaScript"
- do not redefine the img prop in the request item component per eslint. also require the img and status props
- export the img variable as defaultImage from args.js and use it in the request item story

35 request item v2

---

src/assets/theme/global.css
src/components/Button/Button.jsx
src/components/Title/Title.jsx
src/compounds/Item/Item.jsx
src/compounds/LinkGroup/LinkGroup.jsx
src/compounds/RequestItem/RequestItem.jsx
src/compounds/RequestItem/request-item.css
src/compounds/RequestList/RequestList.jsx

- formats request list page so that the requests will be the correct width inside their flexbox
- changes a few margin class names so they are consistent to what they will be with bootstrap
- adds an additional classes (`addClass`) prop to buttons
https://github.com/scientist-softserv/webstore/pull/58

Request List Page Layout 

---

.storybook/preview.js
src/assets/theme/bootstrap-preview.scss
src/assets/theme/global.scss

Moves bootstrap import into preview file so that it doesn't bleed into the webstore & mess up default overrides

fix bootstrap import setup

---

src/components/StatusBar/StatusBar.jsx
src/components/StatusBar/StatusBar.stories.jsx
src/resources/args.js

- status are configured in the webstore app so we do not need the requestLabel prop in the status array anymore
- ref: https://github.com/scientist-softserv/webstore/pull/76
https://user-images.githubusercontent.com/29032869/206051810-f9ffb5a5-1f20-4f2e-abb5-30d32043ee1d.mp4

update status bar

---

src/compounds/RequestStats/RequestStats.jsx
src/compounds/RequestStats/RequestStats.stories.jsx
src/compounds/RequestStats/request-stats.css

- using the react bs card component to render request stats
- remove the detailsColor, headerColor and projectCode props
- [chris said](https://assaydepot.slack.com/archives/C03FZDALABG/p1670007670770879) we don't need project code
- the color props aren't needed since we're using bootstrap
- add an `addClass` prop so the header can be styled
- pass in a billing and shipping object that has the id and address so the id can be used as a unique key value
https://user-images.githubusercontent.com/29032869/206732739-d384e96c-d3af-4b83-892e-efc0dc84d592.mp4

85-refactor-request-stats

---

src/compounds/ActionsGroup/ActionsGroup.stories.jsx
src/compounds/ActionsGroup/actions/SendMessage.jsx
src/resources/utilityFunctions.js

- configure SendMessage to accept file uploads
- able to upload files from multiple locations
- able to delete files
- returns a string to the webstore that includes a "name" property (re: [this issue](https://github.com/assaydepot/scientist_api_v2/issues/167#issuecomment-1352223010))
https://user-images.githubusercontent.com/29032869/207733590-034c05ac-3672-455c-b5df-78ca43aa94d8.mp4
- [converting multiple images to base64](https://stackoverflow.com/a/58960971/8079848)

63 action v2

---

src/components/CollapsibleSection/CollapsibleSection.jsx
src/components/CollapsibleSection/collapsible-section.scss

- the accordion is collapsed by default
- fix comment and styling on collapsible section
- add margin after each section in the collapsible section

Another collapsible section refactor

---

.eslintrc.json
src/components/AdditionalInfo/AdditionalInfo.jsx
src/compounds/ActionsGroup/actions/SendMessage.jsx
src/resources/utilityFunctions.js

brings the UI from the message attachments into the Additional Info component that is used on the request forms
https://github.com/scientist-softserv/webstore-component-library/issues/106
When attachments are uploaded (on both messages and request forms) there is text that says "No file chosen"
- this is built into bootstrap 
- I left a comment/question on a related BS issue here, so if they respond we can follow up and change this: https://github.com/twbs/bootstrap/discussions/33880#discussioncomment-4606560

Request attachments

---

src/components/AdditionalInfo/AdditionalInfo.jsx
src/resources/utilityFunctions.js

- The datepicker in the additional info component will now have a minimum date of one day
- The default date when a user opens the date picker will now be one week
https://share.getcloudapp.com/4gu4eyL0

Add minimum date of a day and default date of a week

---

package.json

now that we are using the published package in the webstore, the local linking doesn't work as outlined in the [webstore readme](https://github.com/scientist-softserv/webstore#component-library-dev-mode).
- rename the package so it matches the published package name

repair the broken linking

---

src/compounds/Item/CardBody.jsx
src/compounds/Item/Item.jsx
src/compounds/ItemGroup/ItemGroup.jsx

the `fromItemGroup` prop is no longer necessary because we need to pass the `id` as a query param in both instances of the `Item` component
- remove the no longer needed `fromItemGroup` prop

remove fromItemGroup

---

src/components/AdditionalInfo/AdditionalInfo.jsx

the `proposed_deadline_str` property that we send to the api when creating a request expects a string. in the event the user has selected that there isn't a proposal deadline, we want to send back an empty string instead of `null`.

93-no-proposed-deadline

---

src/components/Error/Error.jsx
src/components/Error/Error.stories.jsx
src/components/Notice/Notice.jsx
src/components/Notice/Notice.stories.jsx
src/components/index.js

~since I renamed the file, it appears as an entirely new file. In order to see the actual changes (which there are still plenty of), look at [this commit](https://github.com/scientist-softserv/webstore-component-library/pull/137/commits/a1d9c5c9d80768ba7266e6277957008aa5bbcbe4). The second commit was simply updating all instances of `Error` to `Notice`~
We needed to use alerts for reasons other than errors so a refactor on the Error component was done so it was more flexible. 
- can display formatted error messages
- can display regular text alerts
<details>
<summary>Default</summary>
</details>
<details>
<summary>Error</summary>
</details>
<details>
<summary>Unauthenticated user</summary>
</details>

136 refactor error

---

src/compounds/RequestList/RequestList.jsx
src/compounds/RequestList/RequestList.stories.jsx

add backup text for when there are no requests in the request list.
Closes #157 
Alternate story: when requests is an empty array

157- Account for 0 requests

---

src/compounds/RequestItem/RequestItem.jsx
src/compounds/RequestItem/RequestItem.stories.jsx
src/compounds/RequestList/RequestList.jsx
src/resources/args.js

ref: https://github.com/scientist-softserv/webstore/issues/171
related to: https://github.com/scientist-softserv/webstore/pull/221
updates to go along with changing the webstore to reference a request by its uuid instead of its id. nothing has changed from a ux perspective. the only ui change is the url.
- pass the href object from request list to request item
- update the value of "href" for a request item to pass an object with "pathname" and "query" values for consistency with other links in the app

171 request UUID

---

src/assets/fontawesome.js
src/components/FilesTable/FilesTable.jsx
src/components/Link/Link.jsx
src/compounds/ActionsGroup/ActionsGroup.jsx
src/compounds/ActionsGroup/actions/ViewFiles.jsx

- a user can now add attachments from the request page "view files" action
- they can also download these attachments
- users could not add additional attachments after creating a request except through sending messages
https://share.getcloudapp.com/v1uP5dz7
#152 
Webstore PR: https://github.com/scientist-softserv/webstore/pull/222

152 Add attachments

---

src/components/FilesTable/FilesTable.jsx
src/components/Link/Link.jsx
src/components/Link/Link.stories.jsx

- make the label required on a link. however, it can be an empty string if the desire is to only show an icon
<details>
<summary>link with just text</summary>
</details>
<details>
<summary>link with text and an icon</summary>
</details>
<details>
<summary>link with just an icon</summary>
</details>

165 link proptypes

---

src/components/Notice/Notice.jsx
src/compounds/Document/Document.jsx

- enables accepting a SOW from the button in the Document component
- makes the header of the document component have a background color so it is consistent to what we have in ViewFiles
- adds a Notice in the document component that shows when a sow is accepted. 
- Adds `addClass` and `onClose` optional props to the notice to make it more flexible/allows it to close from the Document component.
ticket: https://github.com/scientist-softserv/webstore/issues/137
webstore pr: https://github.com/scientist-softserv/webstore/pull/229

137 accept sow
