- src/compounds/Item/Item.jsx
- src/compounds/Item/Item.stories.jsx
- src/compounds/Item/ItemLoading.jsx
- src/compounds/Item/item.css
- src/compounds/ItemGroup/ItemGroup.jsx
- src/compounds/ItemGroup/ItemGroup.stories.jsx
- src/compounds/ItemGroup/item-group.css
- created the ItemLoading component
- using ItemLoading in the Item stories
- using ItemLoading in the ItemGroup stories
| item | item group |
| --- | --- |
|![image](https://user-images.githubusercontent.com/29032869/201984962-329fe4b6-8dc1-4c15-8491-80b0f15599a6.png) | ![image](https://user-images.githubusercontent.com/29032869/201984897-efdb8c4a-a2d0-4bbd-9a18-46ca961ac1a8.png)|
> 24 item loading

- package-lock.json
- package.json
- src/components/Loading/Loading.jsx
- src/components/Loading/Loading.stories.jsx
- src/components/index.js
- created a Loading spinner to be used when we're waiting for an api call to complete
https://user-images.githubusercontent.com/29032869/202020014-a6deb4e0-47db-44a2-b5ab-8602de270388.mp4
- https://mhnpd.github.io/react-loader-spinner/docs/intro
> 24 loading

- src/compounds/RequestItem/RequestItem.jsx
- src/compounds/RequestItem/RequestItem.stories.jsx
- src/compounds/RequestItem/request-item.css
ref: #35 
- create the initial request item and stories
> 35 request item

- src/assets/theme/global.css
- src/components/Title/Title.jsx
- src/compounds/Item/Item.jsx
- src/compounds/Item/item.css
- src/compounds/LinkGroup/LinkGroup.jsx
- replace the global header and paragraph margin styling with a base of 0 and then add custom classes
- use the custom classes in a few components
- ...
> Refactor globals

- src/components/Button/Button.jsx
- src/components/Button/Button.stories.jsx
- src/components/Button/button.css
- refactor the button component to fit our needs
> 53 refactor button

- src/compounds/Item/Item.stories.jsx
- src/compounds/ItemGroup/ItemGroup.jsx
- remove references to the "primary" button prop
> 53 button refactor 2

- src/compounds/Item/Item.jsx
- src/compounds/Item/item.css
- src/compounds/LinkedButton/LinkedButton.jsx
- src/compounds/LinkedButton/LinkedButton.stories.jsx
- src/compounds/LinkedButton/linked-button.css
- src/compounds/index.js
- src/index.js
- linked buttons are created to prevent needing to wrap every button with a next link
- https://dev.to/darksmile92/js-use-spread-to-exclude-properties-1km9
> 53 linked button

- src/components/Title/Title.jsx
- src/components/Title/title.css
- src/compounds/ItemGroup/ItemGroup.jsx
- src/compounds/TitledTextBox/TitledTextBox.jsx
- Remove default title styling
- add additional size to title options
I went through each component that rendered the Title component. these are the only 2 that needed sizing returned.
> title updates

- src/compounds/RequestStats/RequestStats.jsx
- src/compounds/RequestStats/RequestStats.stories.jsx
- src/compounds/RequestStats/request-stats.css
- rendering data correctly in request stats
> 1 request stats

- babel-plugin-macros.config.js
- package-lock.json
- package.json
example of use:
Icons must be imported individually
> adds fontawesome to component lib

- README.md
- add more detail to the fontawesome directions
- linting
- add missing sections to the table of contents
> expand the fontawesome readme directions

- src/components/Title/title.css
- the title should not have a title cursor at all times
> update title cursor

- src/components/CollapsibleSection/CollapsibleSection.jsx
- src/components/CollapsibleSection/CollapsibleSection.stories.jsx
- src/components/CollapsibleSection/collapsible-section.scss
- src/components/index.js
Add a collapsible accordion component to be used on the single request page for the description
Description without html text
https://share.getcloudapp.com/nOu1nODn
Description with html text
https://share.getcloudapp.com/4gu4OAmv
> Description accordion

- src/compounds/Messages/Messages.jsx
- src/compounds/Messages/Messages.stories.jsx
- src/resources/args.js
- refactor the messages to show a default message when there are no messages
> 93 messages refactor

- src/compounds/Messages/Messages.jsx
- remove unnecessary class
- edit message
> 93 edit message

- src/assets/theme/global.scss
- src/components/CollapsibleSection/CollapsibleSection.jsx
- src/components/CollapsibleSection/collapsible-section.scss
-changes sizing of additional info (collapsible section) for single request page
> Additional info refactor

- src/compounds/Messages/Messages.jsx
change the message:id proptype to be a number
> 93 messages proptype

- src/assets/theme/global.scss
- src/components/AdditionalInfo/AdditionalInfo.jsx
- src/components/BlankRequestForm/BlankRequestForm.jsx
- src/components/ShippingDetails/ShippingDetails.jsx
- validates the request form
- uses bootstrap validation for ui
https://github.com/scientist-softserv/webstore/issues/106
https://share.getcloudapp.com/NQu4xYro
- we may need to revisit bootstrap validation after we bring in the dynamic json schema form
> Form validation

- src/compounds/Item/Item.jsx
- src/compounds/Item/ItemLoading.jsx
- fix the default widths and prop types so lint is happy
> fix default widths

- src/compounds/ItemPage/ItemPage.jsx
- src/compounds/ItemPage/ItemPage.stories.jsx
Updates the button on the service page to have the correct path so that it will show the dynamic form / the new request form of that service
#120 
webstore pr: https://github.com/scientist-softserv/webstore/pull/122
https://share.getcloudapp.com/9ZuzKZyd
> Update service button to have the correct path

- src/components/BlankRequestForm/BlankRequestForm.jsx
- src/compounds/ItemPage/ItemPage.jsx
ref https://github.com/scientist-softserv/webstore/issues/63
- update the state variable names being passed back from the blank request form
- set the item page image default width again
> 63 blank request

- package-lock.json
- package.json
messed up a previous release, so I need to manually change the local version so I can do a new release.
> set the version to 0.1.9

- src/components/Error/Error.jsx
- src/components/Error/Error.stories.jsx
- src/components/index.js
- src/compounds/ItemGroup/ItemGroup.jsx
- creates an error component to be used on pages that might throw an error
https://github.com/scientist-softserv/webstore-component-library/issues/25
default (this example has multiple errors so would be in dev)
alternate (dismissible)
> Error component

- src/compounds/Header/Header.jsx
- src/compounds/Header/Header.stories.jsx
- src/resources/args.js
ref: https://github.com/scientist-softserv/webstore-component-library/issues/128
- refactor the header to accept nav links instead of hard coding them
> 128 refactor header

- src/compounds/Messages/MessageCardBody.jsx
fixes the message formatting for messages coming from the marketplace
Closes #133
> fix formatting

- src/components/LineItemsTable/LineItemsTable.jsx
- src/compounds/Document/Document.jsx
- src/compounds/Item/CardBody.jsx
- src/compounds/Item/Item.jsx
do not use default imports from react-bootstrap anywhere. this is messing up the docker build for some reason
> uniform react-bootstrap imports

- src/compounds/ActionsGroup/ActionsGroup.jsx
uncomments the message sending functionality
webstore PR: https://github.com/scientist-softserv/webstore/pull/213
webstore ticket: https://github.com/scientist-softserv/webstore/issues/156
> bring back sending messages
